### ISSUE TITLE
Returning Empty DataFrame

### ISSUE THREAD

**Issue by jxng** [sundios/people-also-ask#3]
Keeps returning with an empty data frame regardless of the keyword.

**Comment by sundios** [comment]
Hey, this is because the div I selected in the current script has changed. I will try to fix it soon. 

If you fix it please create a PR and I can merge it

**Comment by fennybz** [comment]
> Keeps returning with an empty data frame regardless of the keyword.

I am also facing the same issue, if you can say what could be the long term solution to it will also help.

**Comment by ramazan-umutlu** [comment]
Do u have any news about this? I'm tried to upgrade but can't.

**Comment by sundios** [comment]
Hey why dont you use  [https://simpletools.io/people-also-ask](https://simpletools.io/people-also-ask) it works well.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/8944638/181027543-ae01fb54-cc16-483f-b82c-5c2f977f2599.png">

**Comment by sundios** [comment]
The problem has been solved. Closing this ticket

**Comment by ramazan-umutlu** [comment]
I'm collecting more than 10k keyword something custom works better.
